Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -10,15 +10,16 @@ phases:
     runtime-versions:
       java: corretto17
     commands:
-      - echo "롼경 변수 테스트 $DOCKER_USER_NAME"
+      - echo "Docker ID: $DOCKER_USER_NAME"
+      - echo "Docker Password: $DOCKER_PASSWORD"
       - echo "Docker Credential 로드 완료"
       - echo "현재 브랜치: ${CODEBUILD_SOURCE_VERSION##*/}"
       - |
         BRANCH="${CODEBUILD_SOURCE_VERSION##*/}"
-        case "$BRANCH" in
-          main|develop) echo "$BRANCH 브랜치 빌드 시작" ;;
-          *) echo "ERROR: 허용되지 않은 브랜치"; exit 1 ;;
-        esac
+        if [[ "$BRANCH" != "main" && "$BRANCH" != "develop" ]]; then
+          echo "ERROR: 허용되지 않은 브랜치"; exit 1;
+        fi
+        echo "$BRANCH 브랜치 빌드 시작"
       - chmod +x ./gradlew
 
   build:
